### ISSUE TITLE
Windows WSL2 Ruby Installation

### ISSUE THREAD

**Issue by hroh795** [learn-co-curriculum/phase-0-wsl2-env-ruby#13]
### Canvas Link

https://learning.flatironschool.com/courses/6106/pages/windows-wsl2-ruby-installation?module_item_id=470976

### Concern

I kept getting errors using rvm install 2.7.4 --default. I went through the troubleshooting on the page but still could not resolve the problem. I asked the TC and he said to use rvm install 3.1.1 --deafulat command and it worked. So I recommend that README should update the Ruby version.

**Comment by lizbur10** [comment]
Hi @hroh795 ! Thanks for the feedback. Once we are able to verify that upgrading to Ruby version 3 will not cause problems for the labs in our curriculum we will make this update.

Thanks for contributing to the Flatiron School curriculum 💙
