### ISSUE TITLE
Copying "code" tags

### ISSUE THREAD

**Issue by theFlexOne** [learn-co-curriculum/phase-0-wsl2-env-ruby#3]
Since these instructions require precise keystrokes, in a specific order, and could cause headaches  for new students (like me) if they make a typo or don't select the entire command with the cursor, it would be nice if there was a clipboard button at the end of every line with a code tag that copies what's inside the code tag. Also, triple clicking a code tag should override the default "highlight line" command and just highlight what's inside the code tag. That last one just seems way too obvious but I never see it.

Just some thoughts

**Comment by graciemcguire** [comment]
Hey @theFlexOne, thanks for raising this issue. We just looked into it and unfortunately making changes (like adding copy buttons) in Github will not be reflected in Canvas. We recommend double checking that you have correctly typed out everything before hitting `Enter`. While it seems tedious, I promise it does become a muscle over time! 😀
Happy coding!
