### ISSUE TITLE
Incorrect ruby version installed

### ISSUE THREAD

**Issue by NicMortelliti** [learn-co-curriculum/phase-0-wsl2-env-ruby#9]
### Canvas Link

https://learning.flatironschool.com/courses/4968/pages/windows-wsl2-ruby-installation?module_item_id=321581

### Concern

In the section "Install Ruby Version 2.6.1 on Ubuntu", step 3 of the Action Items, version 2.6.1 of RVM is installed. However, later when the validation script is run, the Default RVM item says Ruby should be 2.7.4.

### Suggested Changes

I believe the Ruby install instructions should be updated to install 2.7.4 instead of 2.6.1.

**Comment by graciemcguire** [comment]
Hello @Leavingvalhalla , and thank you for spotting this issue and providing feedback!

We have updated the GitHub repo and believe your issue to have been resolved. 
Note, however, that if you are working in Canvas the changes may not show up 
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
